#NGROK_AUTH_TOKEN: YOUR_AUTH_TOKEN

# Your Teachable Machine Ai model Link
TEACHABLE_MACHINE_URL: https://teachablemachine.withgoogle.com/models/XXXXXX/

# FACING MODE OF CAMERA
# Eg: front and back
DEFAULT_CAMERA_FACING: "front"










#################################################################
############ Made by Sanay George Varghese ######################
#################################################################
